// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF-lALNsNuTPvY7ENStSeXakZ1id-dXn8',
    appId: '1:794722730903:web:62bbe57db32198df3abad2',
    messagingSenderId: '794722730903',
    projectId: 'uraine-platform',
    authDomain: 'uraine-platform.firebaseapp.com',
    storageBucket: 'uraine-platform.firebasestorage.app',
    measurementId: 'G-JTD7DTT704',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOx2fwbKq_4wQF9C0XkPD0Vo3FDBZZYq4',
    appId: '1:794722730903:android:a29a4154dafe8e923abad2',
    messagingSenderId: '794722730903',
    projectId: 'uraine-platform',
    storageBucket: 'uraine-platform.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABjuJXoOeP_5j9SmclQ4Gh_zzz18sR2Vk',
    appId: '1:794722730903:ios:70782248c105d0493abad2',
    messagingSenderId: '794722730903',
    projectId: 'uraine-platform',
    storageBucket: 'uraine-platform.firebasestorage.app',
    iosBundleId: 'com.example.uraineWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABjuJXoOeP_5j9SmclQ4Gh_zzz18sR2Vk',
    appId: '1:794722730903:ios:70782248c105d0493abad2',
    messagingSenderId: '794722730903',
    projectId: 'uraine-platform',
    storageBucket: 'uraine-platform.firebasestorage.app',
    iosBundleId: 'com.example.uraineWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBF-lALNsNuTPvY7ENStSeXakZ1id-dXn8',
    appId: '1:794722730903:web:2f1fc23ec293ed123abad2',
    messagingSenderId: '794722730903',
    projectId: 'uraine-platform',
    authDomain: 'uraine-platform.firebaseapp.com',
    storageBucket: 'uraine-platform.firebasestorage.app',
    measurementId: 'G-TD5MS3Z8LB',
  );
}
